export const GAMES = [
  { slug:'2048',        name:'2048',         emoji:'🔢', scoreHint:'best tile', url:'/2048',        desc:'Slide and merge matching tiles until you reach 2048.' },
  { slug:'pong',        name:'Pong',         emoji:'🏓', scoreHint:'returns',   url:'/pong',         desc:'Classic paddle game. Play against the computer!' },
  { slug:'snake',       name:'Snake',        emoji:'🐍', scoreHint:'length',    url:'/snake',        desc:'Eat food, grow longer, avoid walls and yourself.' },
  { slug:'tictactoe',   name:'Tic-Tac-Toe',  emoji:'⭕', scoreHint:'wins',      url:'/tictactoe',    desc:'Play vs AI or local 2‑player. Try to get 3 in a row!' },
  { slug:'rps',         name:'Rock Paper Scissors', emoji:'✂️', scoreHint:'streak', url:'/rps',       desc:'Quick rounds. Build a winning streak!' },
  { slug:'memory',      name:'Memory',       emoji:'🧠', scoreHint:'pairs',     url:'/memory',       desc:'Flip cards to find pairs. Solo or pass‑and‑play.' },
  { slug:'breakout',    name:'Breakout',     emoji:'🎯', scoreHint:'bricks',    url:'/breakout',     desc:'Break all the bricks. Advance levels and score big.' },
  { slug:'connect4',    name:'Connect 4',    emoji:'🟡', scoreHint:'wins',      url:'/connect4',     desc:'Connect four in a row. 2‑player or vs a simple AI.' },
  { slug:'minesweeper', name:'Minesweeper',  emoji:'💣', scoreHint:'boards',    url:'/minesweeper',  desc:'Clear the board without detonating mines.' },
  { slug:'flappy',      name:'Flappy Bird',  emoji:'🐦', scoreHint:'distance',  url:'/flappy',       desc:'Tap to fly through pipes. Different skins and worlds.' },
  { slug:'dino',        name:'Dino Run',     emoji:'🦖', scoreHint:'distance',  url:'/dino',         desc:'Endless runner with speed ramp and multipliers.' },
  { slug:'spaceinvaders', name:'Space Invaders', emoji:'👾', scoreHint:'waves', url:'/spaceinvaders', desc:'Classic shooter. Clear waves and dodge fire!' },
  { slug:'frogger',     name:'Frogger',      emoji:'🐸', scoreHint:'crossings', url:'/frogger',      desc:'Hop across traffic and rivers to reach safety.' },
  { slug:'minigolf',    name:'Pocket Mini Golf', emoji:'⛳', scoreHint:'low score', url:'/minigolf',   desc:'Pull back and putt through hazards across 3 compact holes.' },
  { slug:'micro-mario', name:'Micro Mario',  emoji:'🍄', scoreHint:'coins',     url:'/mario',        desc:'Tiny platformer. Collect coins and reach the flag.' },
  { slug:'ski',         name:'Retro Downhill Ski', emoji:'⛷️', scoreHint:'distance', url:'/ski',    desc:'Dodge trees and rocks as you race down the mountain!' },
  { slug:'homerunderby', name:'Home Run Derby', emoji:'⚾', scoreHint:'homeruns', url:'/homerunderby/', desc:'Time your swing to crush home runs before you rack up 10 outs.' },
  { slug:'micro-rc-racer', name:'Micro RC Racer', emoji:'🏎️', scoreHint:'best lap', url:'/microrc', desc:'Top-down RC dirt racing with tank steering and slippery drifts.' },
  { slug:'pacman',      name:'Pac-Man',      emoji:'🟡', scoreHint:'score',     url:'/pacman',       desc:'Eat pellets, outsmart ghosts, and clear multiple levels.' },
  { slug:'pokemon',     name:'Pokemon',      emoji:'⚡', scoreHint:'badges',    url:'/pokemon',      desc:'Build your team, battle trainers, and collect badges.' },
];

