export const GAMES = [
  { slug:'2048',           name:'2048',                emoji:'\u{1F522}', scoreHint:'best tile',  url:'/2048',          desc:'Slide and merge matching tiles until you reach 2048.', earnsCoins:true },
  { slug:'pong',           name:'Pong',                emoji:'\u{1F3D3}', scoreHint:'returns',    url:'/pong',          desc:'Classic paddle game. Play against the computer!', earnsCoins:true },
  { slug:'snake',          name:'Snake',               emoji:'\u{1F40D}', scoreHint:'length',     url:'/snake',         desc:'Eat food, grow longer, avoid walls and yourself.', earnsCoins:true },
  { slug:'tictactoe',      name:'Tic-Tac-Toe',         emoji:'\u274C',    scoreHint:'wins',       url:'/tictactoe',     desc:'Play vs AI or local 2-player. Try to get 3 in a row!', earnsCoins:true },
  { slug:'rps',            name:'Rock Paper Scissors', emoji:'\u270A',    scoreHint:'streak',     url:'/rps',           desc:'Quick rounds. Build a winning streak!', earnsCoins:true },
  { slug:'memory',         name:'Memory',              emoji:'\u{1F9E0}', scoreHint:'pairs',      url:'/memory',        desc:'Flip cards to find pairs. Solo or pass-and-play.', earnsCoins:true },
  { slug:'hangman',        name:'Hangman',             emoji:'\u{1FAA2}', scoreHint:'wins',       url:'/hangman',       desc:'Guess letters to solve words. Play against computer or challenge a friend.', earnsCoins:true },
  { slug:'breakout',       name:'Breakout',            emoji:'\u{1F9F1}', scoreHint:'bricks',     url:'/breakout',      desc:'Break all the bricks. Advance levels and score big.', earnsCoins:true },
  { slug:'connect4',       name:'Connect 4',           emoji:'\u{1F7E1}', scoreHint:'wins',       url:'/connect4',      desc:'Connect four in a row. 2-player or vs a simple AI.', earnsCoins:true },
  { slug:'minesweeper',    name:'Minesweeper',         emoji:'\u{1F4A3}', scoreHint:'boards',     url:'/minesweeper',   desc:'Clear the board without detonating mines.', earnsCoins:true },
  { slug:'flappy',         name:'Flappy Bird',         emoji:'\u{1F426}', scoreHint:'distance',   url:'/flappy',        desc:'Tap to fly through pipes. Different skins and worlds.', earnsCoins:true },
  { slug:'dino',           name:'Dino Run',            emoji:'\u{1F996}', scoreHint:'distance',   url:'/dino',          desc:'Endless runner with speed ramp and multipliers.', earnsCoins:true },
  { slug:'doodlejump',     name:'Doodle Jump',         emoji:'\u{1FA82}', scoreHint:'height',     url:'/doodlejump',    desc:'Hop between platforms, climb higher, and avoid falling off-screen.', earnsCoins:true },
  { slug:'spaceinvaders',  name:'Space Invaders',      emoji:'\u{1F47E}', scoreHint:'waves',      url:'/spaceinvaders', desc:'Classic shooter. Clear waves and dodge fire!', earnsCoins:true },
  { slug:'frogger',        name:'Frogger',             emoji:'\u{1F438}', scoreHint:'crossings',  url:'/frogger',       desc:'Hop across traffic and rivers to reach safety.', earnsCoins:true },
  { slug:'minigolf',       name:'Pocket Mini Golf',    emoji:'\u26F3',    scoreHint:'low score',  url:'/minigolf',      desc:'Pull back and putt through hazards across 3 compact holes.', earnsCoins:false },
  { slug:'micro-mario',    name:'Micro Mario',         emoji:'\u{1F344}', scoreHint:'coins',      url:'/mario',         desc:'Tiny platformer. Collect coins and reach the flag.', earnsCoins:true },
  { slug:'ski',            name:'Retro Downhill Ski',  emoji:'\u26F7\uFE0F', scoreHint:'distance', url:'/ski',         desc:'Dodge trees and rocks as you race down the mountain!', earnsCoins:true },
  { slug:'homerunderby',   name:'Home Run Derby',      emoji:'\u26BE',    scoreHint:'homeruns',   url:'/homerunderby/', desc:'Time your swing to crush home runs before you rack up 10 outs.', earnsCoins:true },
  { slug:'micro-rc-racer', name:'Micro RC Racer',      emoji:'\u{1F3CE}\uFE0F', scoreHint:'best lap', url:'/microrc',   desc:'Top-down RC dirt racing with tank steering and slippery drifts.', earnsCoins:false },
  { slug:'neonrally',      name:'Neon Rally',          emoji:'\u{1F3C1}', scoreHint:'position',   url:'/neonrally',     desc:'Race AI rivals through neon turns, chain boosts, and finish 3 laps before time runs out.', earnsCoins:true },
  { slug:'pacman',         name:'Pac-Man',             emoji:'\u{1F7E1}', scoreHint:'score',      url:'/pacman',        desc:'Eat pellets, outsmart ghosts, and clear multiple levels.', earnsCoins:true },
  { slug:'pokemon',        name:'Pokemon',             emoji:'\u{1F9E2}', scoreHint:'badges',     url:'/pokemon',       desc:'Build your team, battle trainers, and collect badges.', earnsCoins:true },
  { slug:'tetris',         name:'Tetris',              emoji:'\u{1F9E9}', scoreHint:'lines',      url:'/tetris',        desc:'Rotate, stack, and clear lines as speed ramps up each level.', earnsCoins:true },
  { slug:'asteroids',      name:'Asteroids',           emoji:'\u2604\uFE0F', scoreHint:'waves',   url:'/asteroids',     desc:'Thrust, rotate, and blast drifting asteroids across endless waves.', earnsCoins:true },
  { slug:'bomberman',      name:'Bomberman Lite',      emoji:'\u{1F4A5}', scoreHint:'level',      url:'/bomberman',     desc:'Drop bombs, break crates, clear enemies, and escape each maze.', earnsCoins:true },
  { slug:'treasuremaze',   name:'Treasure Maze',       emoji:'\u{1F48E}', scoreHint:'level',      url:'/treasuremaze',  desc:'Navigate twisting mazes, collect every gem, and escape the guards.', earnsCoins:true },
  { slug:'boxquest',       name:'Box Quest',           emoji:'\u{1F4E6}', scoreHint:'moves',      url:'/boxquest',      desc:'Push crates onto glowing goal pads across multi-level puzzle rooms.', earnsCoins:true },
  { slug:'waterballoon',   name:'Water Balloon Code Duel', emoji:'\u{1F4A7}', scoreHint:'wins',   url:'/waterballoon',  desc:'Two players script moves, pass the device, and watch both turns resolve simultaneously.', earnsCoins:true },
  { slug:'whackamole',     name:'Whack-a-Mole Blitz',  emoji:'\u{1F528}', scoreHint:'score',      url:'/whackamole',    desc:'Race the clock by smashing moles, chaining streaks, and avoiding bomb traps.', earnsCoins:true },
  { slug:'colorcatch',     name:'Color Catch Arcade',  emoji:'\u{1F308}', scoreHint:'score',      url:'/colorcatch',    desc:'Match bucket colors to falling drops, chain combos, and survive all three stages.', earnsCoins:true },
  { slug:'orbitalrescue',  name:'Orbital Rescue',      emoji:'\u{1F6F8}', scoreHint:'rescues',    url:'/orbitalrescue', desc:'Pilot a rescue craft, recover stranded pilots, and survive escalating debris waves.', earnsCoins:true },
  { slug:'lightsout',      name:'Lights Out Lab',      emoji:'\u{1F4A1}', scoreHint:'levels',     url:'/lightsout',     desc:'Flip cross-neighbor tiles, clear every light, and solve escalating puzzle boards.', earnsCoins:true },
  { slug:'pinball',        name:'Neon Pinball Rush',   emoji:'\u{1F3B0}', scoreHint:'score',      url:'/pinball',       desc:'Launch, flip, and chain bumper combos in a neon table run before your balls run out.', earnsCoins:true },
];

