import {connect} from "/src/net/multiplayerClient.js";
import {reportGameOutcome} from "/src/core/outcomes.js";
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),display=Boolean(params.get("display")),embedded=params.get("embedded")==="1";let conn,snap,room="",reported=false,audio,playedAudio=new Set(),serverOffset=0;
const colors=["#27d9e8","#ffc943","#ff637e","#ae7aff"];
function tone(lane,at){if(!audio)return;const osc=audio.createOscillator(),gain=audio.createGain(),freq=[196,247,294,370][lane];osc.type="triangle";osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.035,audio.currentTime+.012);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.16);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+.18)}
function render(){if(!snap)return;const now=Date.now()+serverOffset,phase=snap.phase||"lobby",players=snap.players||[],notes=snap.notes||[];$("code").textContent=room||snap.roomId||"----";$ ("phase").textContent=phase==="racing"?"Hit the notes on the line!":phase.replaceAll("_"," ");const left=phase==="racing"?Math.max(0,(Number(snap.phaseEndsAt)-now)/1000):phase==="countdown"?Math.max(0,(Number(snap.phaseEndsAt)-now)/1000):0;$ ("clock").textContent=phase==="racing"?`0:${String(Math.ceil(left)).padStart(2,"0")}`:phase==="countdown"?`${Math.ceil(left)}`:"♪";$ ("round").textContent=phase==="podium"?"SET COMPLETE":phase==="racing"?"RIFF RALLY · 60 NOTES":phase==="countdown"?"GET READY":"LOBBY";
const board=$("scores");board.textContent="";[...players].sort((a,b)=>(b.score||0)-(a.score||0)).forEach((p,i)=>{const li=document.createElement("li");li.textContent=`${p.rank||i+1}. ${p.avatar||"🎸"} ${p.name} · ${Number(p.score||0).toLocaleString()} · ${p.hits||0} hits · best ${p.bestStreak||0}`;board.append(li)});
const canvas=$("chart"),ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle="#101428";ctx.fillRect(0,0,w,h);const laneW=w/4;for(let lane=0;lane<4;lane++){ctx.fillStyle=lane%2?"#ffffff08":"#ffffff04";ctx.fillRect(lane*laneW,0,laneW,h);ctx.fillStyle=colors[lane];ctx.globalAlpha=.32;ctx.fillRect(lane*laneW+7,0,laneW-14,h);ctx.globalAlpha=1;ctx.fillStyle="#fff";ctx.globalAlpha=.1;ctx.fillRect((lane+1)*laneW-2,0,4,h);ctx.globalAlpha=1;}const hitY=h-78,duration=Number(snap.songLengthMs||30000),reduced=Boolean(snap.partySettings?.reducedMotion);for(const n of notes){const delta=Number(n.at)-now;const y=reduced?hitY-Math.ceil(delta/500)*70:hitY-(delta/3600)*(h-135);if(y<-36||y>hitY+40)continue;const x=n.lane*laneW+laneW/2;ctx.fillStyle=colors[n.lane];ctx.shadowColor=colors[n.lane];ctx.shadowBlur=20;ctx.beginPath();ctx.roundRect(x-laneW*.29,y-17,laneW*.58,34,11);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#141529";ctx.font="bold 18px system-ui";ctx.textAlign="center";ctx.fillText("♪",x,y+7);if(audio&&phase==="racing"&&delta>=0&&delta<=110&&!playedAudio.has(n.id)){playedAudio.add(n.id);tone(n.lane,n.at)}}ctx.strokeStyle="#ffffff";ctx.lineWidth=4;ctx.shadowColor="#fff";ctx.shadowBlur=14;ctx.beginPath();ctx.moveTo(0,hitY);ctx.lineTo(w,hitY);ctx.stroke();ctx.shadowBlur=0;
const racing=phase==="racing",ready=["lobby","podium","ended"].includes(phase);$("start").hidden=display||!ready;$("start").disabled=players.filter(p=>p.connected).length<2;$("pause").hidden=display||!racing;$("resume").hidden=display||phase!=="paused";$("end").hidden=display||!(racing||phase==="countdown");$("hint").textContent=phase==="podium"?"Set complete. Perfect +100 · Good +60 · streak up to +50.":phase==="paused"?"The set is paused. Perfect +100 · Good +60 · streak up to +50.":"Join at /party. Tap on the line. Perfect +100 · Good +60 · streak up to +50.";
if(phase==="podium"&&!reported&&!display&&!embedded){reported=true;const winner=players.length>1&&players[0].score===players[1].score?"tie":"completed";const self=players.find(p=>p.id===snap.selfId)||players[0]||{};reportGameOutcome({slug:"riffrally",result:winner,durationMs:Math.max(0,Number(snap.songFinishedAt)-Number(snap.songStartAt)),metrics:{score:Number(self.score||0),hits:Number(self.hits||0),perfect:Number(self.perfect||0)}})}}
window.render_game_to_text=()=>JSON.stringify({game_key:"riffrally",screen_role:display?"display":"host",phase:snap?.phase||"connecting",room_id:room,notes:snap?.notes?.length||0,players:snap?.players||[]});window.__riffrallySnapshot=()=>snap;async function boot(){if(embedded){addEventListener("message",e=>{if(e.origin===location.origin&&e.data?.type==="party_snapshot"){snap=e.data.snapshot;serverOffset=Number(snap?.serverTime||Date.now())-Date.now();room=e.data.roomId;render()}});return}conn=await connect({gameId:"party",gameKey:"riffrally",role:display?"display":"host",roomId:params.get(display?"display":"room")||"",token:sessionStorage.getItem(`aiandsons-party-host:${params.get("room")||""}`)||""});conn.onStateUpdate(u=>{snap=u.payload?.state||u.payload;serverOffset=Number(snap?.serverTime||Date.now())-Date.now();render()});conn.onEvent(e=>{if(e.type==="welcome"){room=e.payload.roomId||room;if(e.payload.token)sessionStorage.setItem(`aiandsons-party-host:${room}`,e.payload.token);render()}})}
$("start").onclick=async()=>{audio??=new AudioContext();await audio.resume();playedAudio.clear();conn?.sendInput({type:"host",action:"start"});reported=false};$("pause").onclick=()=>conn?.sendInput({type:"host",action:"pause"});$("resume").onclick=()=>conn?.sendInput({type:"host",action:"resume"});$("end").onclick=()=>conn?.sendInput({type:"host",action:"end"});boot();setInterval(render,100);
